# Generated by Django 3.1.6 on 2022-06-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='项目名')),
                ('repo', models.CharField(max_length=128, verbose_name='仓库地址')),
                ('env', models.CharField(choices=[('prod', '正式环境'), ('test', '测试环境')], default='test', max_length=16, verbose_name='环境')),
            ],
        ),
    ]
