# Generated by Django 3.1.6 on 2022-06-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(default='/data/proc/', max_length=128, verbose_name='线上项目地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='servers',
            field=models.ManyToManyField(to='web.Server', verbose_name='关联服务器'),
        ),
    ]
