# Generated by Django 3.1.6 on 2022-06-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_deploy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HookTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='模板名称')),
                ('content', models.TextField(verbose_name='脚本内容')),
                ('hook_type', models.IntegerField(choices=[(2, '下载前'), (4, '下载后'), (6, '发布前'), (8, '发布后')], verbose_name='钩子类型')),
            ],
        ),
    ]
